-- ============================================================
-- CorteYa - Sistema de Gestión de Turnos para Peluquerías
-- Script 01: Creación de Tablas (DDL)
-- Base de datos: Oracle 21c XE - Schema: CORTEYA
-- ============================================================

-- TABLA: CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE        VARCHAR2(100) NOT NULL,
    APELLIDO      VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(150),
    TELEFONO      VARCHAR2(20),
    FECHA_ALTA    DATE DEFAULT SYSDATE
);

-- TABLA: PROFESIONAL
CREATE TABLE PROFESIONAL (
    ID_PROFESIONAL  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100) NOT NULL,
    APELLIDO        VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(150),
    ESPECIALIDAD    VARCHAR2(100)
);

-- TABLA: SERVICIO
CREATE TABLE SERVICIO (
    ID_SERVICIO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE        VARCHAR2(100) NOT NULL,
    DURACION_MIN  NUMBER,
    PRECIO        NUMBER(10,2)
);

-- TABLA: TURNO
CREATE TABLE TURNO (
    ID_TURNO        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE      NUMBER NOT NULL,
    ID_PROFESIONAL  NUMBER NOT NULL,
    ID_SERVICIO     NUMBER NOT NULL,
    FECHA_HORA      DATE NOT NULL,
    HORA_INICIO     VARCHAR2(5),
    ESTADO          VARCHAR2(20) DEFAULT 'PENDIENTE',
    OBSERVACIONES   VARCHAR2(500),
    CONSTRAINT FK_TURNO_CLIENTE     FOREIGN KEY (ID_CLIENTE)     REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_TURNO_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL(ID_PROFESIONAL),
    CONSTRAINT FK_TURNO_SERVICIO    FOREIGN KEY (ID_SERVICIO)     REFERENCES SERVICIO(ID_SERVICIO),
    CONSTRAINT CHK_ESTADO CHECK (ESTADO IN ('PENDIENTE','CONFIRMADO','CANCELADO','FINALIZADO'))
);

-- TABLA: AUDITLOG
CREATE TABLE AUDITLOG (
    ID_LOG          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TURNO        NUMBER,
    ESTADO_ANTERIOR VARCHAR2(20),
    ESTADO_NUEVO    VARCHAR2(20),
    USUARIO         VARCHAR2(100),
    FECHA_HORA      DATE DEFAULT SYSDATE
);
