-- ============================================================
-- CorteYa - Script 01: Tablas y restricciones
-- Base de datos: Oracle 21c XE - Esquema: CORTEYA
-- Ejecutar conectado como CORTEYA.
-- ============================================================

CREATE TABLE CLIENTE (
    ID_CLIENTE     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE         VARCHAR2(100) NOT NULL,
    APELLIDO       VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(150) NOT NULL UNIQUE,
    TELEFONO       VARCHAR2(20),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE PROFESIONAL (
    ID_PROFESIONAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE         VARCHAR2(100) NOT NULL,
    APELLIDO       VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(150) NOT NULL UNIQUE,
    ESPECIALIDAD   VARCHAR2(100)
);

CREATE TABLE SERVICIO (
    ID_SERVICIO  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE       VARCHAR2(100) NOT NULL,
    DURACION_MIN NUMBER        NOT NULL,
    PRECIO       NUMBER(10,2)  NOT NULL,
    CONSTRAINT CHK_SERVICIO_DURACION CHECK (DURACION_MIN > 0),
    CONSTRAINT CHK_SERVICIO_PRECIO   CHECK (PRECIO >= 0)
);

-- FECHA_HORA guarda el día; HORA_INICIO guarda la hora (HH24:MI).
CREATE TABLE TURNO (
    ID_TURNO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE     NUMBER        NOT NULL,
    ID_PROFESIONAL NUMBER        NOT NULL,
    ID_SERVICIO    NUMBER        NOT NULL,
    FECHA_HORA     DATE          NOT NULL,
    HORA_INICIO    VARCHAR2(5)   NOT NULL,
    ESTADO         VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
    OBSERVACIONES  VARCHAR2(500),
    CONSTRAINT FK_TURNO_CLIENTE     FOREIGN KEY (ID_CLIENTE)     REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_TURNO_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL(ID_PROFESIONAL),
    CONSTRAINT FK_TURNO_SERVICIO    FOREIGN KEY (ID_SERVICIO)    REFERENCES SERVICIO(ID_SERVICIO),
    CONSTRAINT CHK_ESTADO     CHECK (ESTADO IN ('PENDIENTE','CONFIRMADO','CANCELADO','FINALIZADO')),
    CONSTRAINT CHK_TURNO_HORA CHECK (REGEXP_LIKE(HORA_INICIO, '^([01][0-9]|2[0-3]):[0-5][0-9]$'))
);

-- DIA_SEMANA: 1 = lunes ... 7 = domingo (norma ISO).
CREATE TABLE DISPONIBILIDAD (
    ID_DISPONIBILIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PROFESIONAL    NUMBER      NOT NULL,
    DIA_SEMANA        NUMBER(1)   NOT NULL,
    HORA_DESDE        VARCHAR2(5) NOT NULL,
    HORA_HASTA        VARCHAR2(5) NOT NULL,
    CONSTRAINT FK_DISP_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL(ID_PROFESIONAL),
    CONSTRAINT CHK_DISP_DIA   CHECK (DIA_SEMANA BETWEEN 1 AND 7),
    CONSTRAINT CHK_DISP_DESDE CHECK (REGEXP_LIKE(HORA_DESDE, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT CHK_DISP_HASTA CHECK (REGEXP_LIKE(HORA_HASTA, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT CHK_DISP_RANGO CHECK (HORA_DESDE < HORA_HASTA),
    CONSTRAINT UQ_DISP UNIQUE (ID_PROFESIONAL, DIA_SEMANA, HORA_DESDE)
);

CREATE TABLE AUDITLOG (
    ID_AUDIT        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TURNO        NUMBER NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(20),
    ESTADO_NUEVO    VARCHAR2(20),
    USUARIO         VARCHAR2(100),
    FECHA_HORA      DATE DEFAULT SYSDATE,
    DETALLE         VARCHAR2(300),
    CONSTRAINT FK_AUDITLOG_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO(ID_TURNO)
);
