-- ============================================================
-- CorteYa - Sistema de Gestión de Turnos para Peluquerías
-- Script 04: Datos de Prueba
-- Base de datos: Oracle 21c XE - Schema: CORTEYA
-- ============================================================

-- CLIENTES
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO) VALUES ('Camila', 'Valdez', 'camila@gmail.com', '3874000001');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO) VALUES ('Juan', 'García', 'juan@gmail.com', '3874000002');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO) VALUES ('María', 'López', 'maria@gmail.com', '3874000003');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO) VALUES ('Carlos', 'Rodríguez', 'carlos@gmail.com', '3874999888');

-- PROFESIONALES
INSERT INTO PROFESIONAL (NOMBRE, APELLIDO, EMAIL, ESPECIALIDAD) VALUES ('Cecilia', 'Gómez', 'cecilia@corteya.com', 'Corte y Color');
INSERT INTO PROFESIONAL (NOMBRE, APELLIDO, EMAIL, ESPECIALIDAD) VALUES ('Sofía', 'González', 'sofia@corteya.com', 'Manicura');
INSERT INTO PROFESIONAL (NOMBRE, APELLIDO, EMAIL, ESPECIALIDAD) VALUES ('Laura', 'Martínez', 'laura@corteya.com', 'Peinado');

-- SERVICIOS
INSERT INTO SERVICIO (NOMBRE, DURACION_MIN, PRECIO) VALUES ('Corte de cabello', 30, 5000);
INSERT INTO SERVICIO (NOMBRE, DURACION_MIN, PRECIO) VALUES ('Peinado', 45, 7000);
INSERT INTO SERVICIO (NOMBRE, DURACION_MIN, PRECIO) VALUES ('Coloración', 90, 15000);
INSERT INTO SERVICIO (NOMBRE, DURACION_MIN, PRECIO) VALUES ('Manicura', 40, 4000);

-- TURNOS
INSERT INTO TURNO (ID_CLIENTE, ID_PROFESIONAL, ID_SERVICIO, FECHA_HORA, HORA_INICIO, ESTADO, OBSERVACIONES)
VALUES (1, 1, 2, TO_DATE('2026-06-25', 'YYYY-MM-DD'), '14:00', 'FINALIZADO', 'Se realizó el corte de cabello, se pagó en efectivo');
INSERT INTO TURNO (ID_CLIENTE, ID_PROFESIONAL, ID_SERVICIO, FECHA_HORA, HORA_INICIO, ESTADO, OBSERVACIONES)
VALUES (2, 1, 1, TO_DATE('2026-06-27', 'YYYY-MM-DD'), '19:30', 'PENDIENTE', 'No se realizó seña');
INSERT INTO TURNO (ID_CLIENTE, ID_PROFESIONAL, ID_SERVICIO, FECHA_HORA, HORA_INICIO, ESTADO, OBSERVACIONES)
VALUES (3, 2, 4, TO_DATE('2026-06-29', 'YYYY-MM-DD'), '20:00', 'CONFIRMADO', 'Señado');

COMMIT;
