-- ============================================================
-- CorteYa - Sistema de Gestión de Turnos para Peluquerías
-- Script 05: Vistas (Views)
-- Base de datos: Oracle 21c XE - Schema: CORTEYA
-- ============================================================

-- VISTA: VW_TURNOS_COMPLETO
-- Muestra todos los turnos con nombre de cliente, profesional y servicio
CREATE OR REPLACE VIEW VW_TURNOS_COMPLETO AS
SELECT
    t.ID_TURNO,
    t.FECHA_HORA,
    t.HORA_INICIO,
    c.NOMBRE || ' ' || c.APELLIDO   AS CLIENTE,
    p.NOMBRE || ' ' || p.APELLIDO   AS PROFESIONAL,
    s.NOMBRE                         AS SERVICIO,
    s.DURACION_MIN,
    s.PRECIO,
    t.ESTADO,
    t.OBSERVACIONES
FROM TURNO t
JOIN CLIENTE     c ON t.ID_CLIENTE     = c.ID_CLIENTE
JOIN PROFESIONAL p ON t.ID_PROFESIONAL = p.ID_PROFESIONAL
JOIN SERVICIO    s ON t.ID_SERVICIO    = s.ID_SERVICIO;

-- VISTA: VW_TURNOS_HOY
-- Muestra los turnos del día actual
CREATE OR REPLACE VIEW VW_TURNOS_HOY AS
SELECT *
FROM VW_TURNOS_COMPLETO
WHERE TRUNC(FECHA_HORA) = TRUNC(SYSDATE)
ORDER BY HORA_INICIO;

-- VISTA: VW_TURNOS_PENDIENTES
-- Muestra únicamente los turnos con estado PENDIENTE o CONFIRMADO
CREATE OR REPLACE VIEW VW_TURNOS_PENDIENTES AS
SELECT *
FROM VW_TURNOS_COMPLETO
WHERE ESTADO IN ('PENDIENTE', 'CONFIRMADO')
ORDER BY FECHA_HORA, HORA_INICIO;

-- VISTA: VW_AGENDA_PROFESIONAL
-- Muestra la agenda futura por profesional
CREATE OR REPLACE VIEW VW_AGENDA_PROFESIONAL AS
SELECT
    p.NOMBRE || ' ' || p.APELLIDO   AS PROFESIONAL,
    p.ESPECIALIDAD,
    t.FECHA_HORA,
    t.HORA_INICIO,
    c.NOMBRE || ' ' || c.APELLIDO   AS CLIENTE,
    s.NOMBRE                         AS SERVICIO,
    t.ESTADO
FROM TURNO t
JOIN CLIENTE     c ON t.ID_CLIENTE     = c.ID_CLIENTE
JOIN PROFESIONAL p ON t.ID_PROFESIONAL = p.ID_PROFESIONAL
JOIN SERVICIO    s ON t.ID_SERVICIO    = s.ID_SERVICIO
WHERE t.FECHA_HORA >= TRUNC(SYSDATE)
  AND t.ESTADO NOT IN ('CANCELADO')
ORDER BY p.APELLIDO, t.FECHA_HORA, t.HORA_INICIO;

-- VISTA: VW_REPORTE_OCUPACION
-- Reporte de cantidad de turnos por profesional y estado
CREATE OR REPLACE VIEW VW_REPORTE_OCUPACION AS
SELECT
    p.NOMBRE || ' ' || p.APELLIDO   AS PROFESIONAL,
    t.ESTADO,
    COUNT(*)                         AS CANTIDAD_TURNOS
FROM TURNO t
JOIN PROFESIONAL p ON t.ID_PROFESIONAL = p.ID_PROFESIONAL
GROUP BY p.NOMBRE || ' ' || p.APELLIDO, t.ESTADO
ORDER BY PROFESIONAL, t.ESTADO;

-- VISTA: VW_HISTORIAL_CLIENTE
-- Historial completo de turnos por cliente
CREATE OR REPLACE VIEW VW_HISTORIAL_CLIENTE AS
SELECT
    c.ID_CLIENTE,
    c.NOMBRE || ' ' || c.APELLIDO   AS CLIENTE,
    c.TELEFONO,
    t.FECHA_HORA,
    t.HORA_INICIO,
    s.NOMBRE                         AS SERVICIO,
    p.NOMBRE || ' ' || p.APELLIDO   AS PROFESIONAL,
    t.ESTADO,
    t.OBSERVACIONES
FROM TURNO t
JOIN CLIENTE     c ON t.ID_CLIENTE     = c.ID_CLIENTE
JOIN PROFESIONAL p ON t.ID_PROFESIONAL = p.ID_PROFESIONAL
JOIN SERVICIO    s ON t.ID_SERVICIO    = s.ID_SERVICIO
ORDER BY c.APELLIDO, t.FECHA_HORA DESC;
